---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK SPEC_OPTS='--format documentation''
bundler_args: --without system_tests development
rvm:
  - 2.5.0
env:
  - PUPPET_GEM_VERSION="~> 5.5"
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
# deploy:
#   provider: puppetforge
#   user: puppet
#   password:
#     secure: ""
#   on:
#     tags: true
#     all_branches: true
#     condition: "$DEPLOY_TO_FORGE = yes"
